GameStore.WebUI/Areas/Admin/Controllers/CategoryController.cs
using System.Threading.Tasks;
using GameStore.Application.Commands.Category.CreateCategory;
using GameStore.Application.Commands.Category.DeleteCategory;
using GameStore.Application.Commands.Category.UpdateCategory;
using GameStore.Application.Exceptions;
using GameStore.Application.Queries.Category.GetAllCategories;
using GameStore.Application.Queries.Category.GetCategoryById;
using GameStore.WebUI.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class CategoryController : BaseController
    {
        public async Task<IActionResult> Index()
        {
            var values = await Mediator.Send(new GetAllCategoriesQuery());
            return View(values);
        }

        public ActionResult Create()
        {
            return View(new CreateCategoryCommand
            {
                Name = "Category name"
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromForm]CreateCategoryCommand createGameCategoryCommand)
        {
            if (ModelState.IsValid)
            {
                await Mediator.Send(createGameCategoryCommand);
                TempData["message"] =
                    $"Category \"{createGameCategoryCommand.Name}\" has been saved.";

                return RedirectToAction(nameof(Index));
            }

            return View(createGameCategoryCommand);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            try
            {
                var category = await Mediator.Send(new GetCategoryByIdQuery { Id = id.Value });
                var categoryUpdateCommand = new UpdateCategoryCommand
                {
                    Id = category.Id,
                    Name = category.Name
                };

                return View(categoryUpdateCommand);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [FromForm]UpdateCategoryCommand updateGameCategoryCommand)
        {
            if (id != updateGameCategoryCommand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await Mediator.Send(updateGameCategoryCommand);
                    TempData["message"] =
                        $"Category \"{updateGameCategoryCommand.Name}\" has been updated.";

                    return RedirectToAction(nameof(Index));
                }
                catch (NotFoundException)
                {
                    return NotFound();
                }
            }

            return RedirectToAction(nameof(Edit));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            try
            {
                var category = await Mediator.Send(new GetCategoryByIdQuery { Id = id.Value });

                return View(category);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await Mediator.Send(new DeleteCategoryCommand { Id = id });
                TempData["message"] = $"Category with id \"{id}\" has been deleted.";

                return RedirectToAction(nameof(Index));
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System.Threading.Tasks;
using GameStore.Application.Queries.Category.GetAllCategories;
using GameStore.Application.Queries.Game.GetAllGames;
using GameStore.Application.ViewModels.Game;
using GameStore.Application.ViewModels.Pagination;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Controllers
{
    public class GameController : BaseController
    {
        public async Task<ViewResult> Index(int? p, string category = null)
        {
            var games = await Mediator.Send(new GetAllGamesQuery
            {
                Pagination = new PageRequestViewModel(p ?? 1, 5),
                Category = category
            });
            var categories = await Mediator.Send(new GetAllCategoriesQuery());

            return View(new GamesListViewModel
            {
                Games = games,
                Categories = categories
            });
        }
    }
}

GameStore.WebUI/Controllers/OrderController.cs
using System.Linq;
using System.Threading.Tasks;
using GameStore.Application.Commands.Order.CreateOrder;
using GameStore.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Controllers
{
    public class OrderController : BaseController
    {
        private readonly Cart cart;

        public OrderController(Cart cart)
        {
            this.cart = cart;
        }

        public ViewResult Checkout() => View(new CreateOrderCommand());

        [HttpPost]
        public async Task<IActionResult> Checkout([FromForm]CreateOrderCommand createOrderCommand)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
         
            if (ModelState.IsValid)
            {
                createOrderCommand.Lines = cart.Lines;
                await Mediator.Send(createOrderCommand);
                return RedirectToAction(nameof(Completed));
            }

            return View(createOrderCommand);
        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

GameStore.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark  mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbar1" aria-controls="navbar1"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar1">
                    <a class="navbar-brand" asp-area="Admin"
                       asp-controller="Admin" asp-action="Index">GameStore</a>
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin"
                               asp-controller="Admin" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin"
                               asp-controller="Game" asp-action="Index">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin"
                               asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin"
                               asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div>
                            <a class="btn btn-sm btn-light"
                               asp-action="Logout" asp-controller="Account">Log Out</a>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark border-top text-muted" style="height: 4em;">
        <div class="container text-light">
            &copy; 2019 - GameStore Admin Panel
        </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>