GameStore.WebUI/Areas/Admin/Controllers/GameController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameStore.Application.Commands.Game.CreateGame;
using GameStore.Application.Commands.Game.DeleteGame;
using GameStore.Application.Commands.Game.UpdateGame;
using GameStore.Application.Exceptions;
using GameStore.Application.Queries.Category.GetAllCategories;
using GameStore.Application.Queries.Game.GetAllGames;
using GameStore.Application.Queries.Game.GetGameById;
using GameStore.Application.Queries.GameCategory.GetAllGameCategoriesByGameId;
using GameStore.Application.ViewModels.Pagination;
using Microsoft.AspNetCore.Mvc;
using GameStore.WebUI.Controllers;
using Microsoft.AspNetCore.Authorization;

namespace GameStore.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class GameController : BaseController
    {
        public async Task<IActionResult> Index(int? p, string category = null)
        {
            var values = await Mediator.Send(new GetAllGamesQuery
            {
                Pagination = new PageRequestViewModel(p ?? 1, 5),
                Category = category
            });

            return View(values);
        }

        public async Task<ActionResult> Create()
        {
            return View(new CreateGameCommand
            {
                Name = "Game name",
                Description = "Game description",
                Price = 1,
                SelectedCategories = new List<int>(),
                AllCategories = await Mediator.Send(new GetAllCategoriesQuery())
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromForm]CreateGameCommand createGameCommand)
        {
            if (ModelState.IsValid)
            {
                await Mediator.Send(createGameCommand);
                TempData["message"] =
                    $"Game \"{createGameCommand.Name}\" has been saved.";

                return RedirectToAction(nameof(Index));
            }

            return View(createGameCommand);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            try
            {
                var game = await Mediator.Send(new GetGameByIdQuery { Id = id.Value });
                var updateGameCommand = new UpdateGameCommand
                {
                    Name = game.Name,
                    Description = game.Description,
                    Id = game.Id,
                    Price = game.Price,
                    SelectedCategories = (await Mediator.Send(
                        new GetAllGameCategoriesByGameIdQuery { Id = game.Id }))
                        .Select(x => x.CategoryId).ToList(),
                    AllCategories = await Mediator.Send(new GetAllCategoriesQuery())
                };

                return View(updateGameCommand);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [FromForm]UpdateGameCommand updateGameCommand)
        {
            if (id != updateGameCommand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await Mediator.Send(updateGameCommand);
                    TempData["message"] =
                        $"Game \"{updateGameCommand.Name}\" has been updated.";

                    return RedirectToAction(nameof(Index));
                }
                catch (NotFoundException)
                {
                    return NotFound();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            try
            {
                var game = await Mediator.Send(new GetGameByIdQuery { Id = id.Value });

                return View(game);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await Mediator.Send(new DeleteGameCommand { Id = id });
                TempData["message"] = $"Game with id \"{id}\" has been deleted.";

                return RedirectToAction(nameof(Index));
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }
    }
}

GameStore.WebUI/Controllers/CartController.cs
using System.Threading.Tasks;
using AutoMapper;
using GameStore.Application.Queries.Game.GetGameById;
using GameStore.Application.ViewModels.Cart;
using GameStore.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Controllers
{
    public class CartController : BaseController
    {
        public CartController(Cart cart, IMapper mapper)
        {
            this.cart = cart;
            this.mapper = mapper;
        }

        private readonly Cart cart;
        private readonly IMapper mapper;

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel()
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public async Task<RedirectToActionResult> AddToCart(int gameId, string returnUrl)
        {
            var game = await Mediator.Send(new GetGameByIdQuery { Id = gameId });

            if (game != null)
            {
                cart.AddItem(mapper.Map<Game>(game), 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public async Task<RedirectToActionResult> RemoveFromCart(int gameId, string returnUrl)
        {
            var game = await Mediator.Send(new GetGameByIdQuery { Id = gameId });

            if (game != null)
            {
                cart.RemoveLine(mapper.Map<Game>(game));
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System.Threading.Tasks;
using GameStore.Application.Queries.Category.GetAllCategories;
using GameStore.Application.Queries.Game.GetAllGames;
using GameStore.Application.ViewModels.Game;
using GameStore.Application.ViewModels.Pagination;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Controllers
{
    public class GameController : BaseController
    {
        public async Task<ViewResult> Index(int? p, string category = null)
        {
            var games = await Mediator.Send(new GetAllGamesQuery
            {
                Pagination = new PageRequestViewModel(p ?? 1, 5),
                Category = category
            });
            var categories = await Mediator.Send(new GetAllCategoriesQuery());

            return View(new GamesListViewModel
            {
                Games = games,
                Categories = categories
            });
        }
    }
}

GameStore.WebUI/Views/Game/Index.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@model GameStore.Application.ViewModels.Game.GamesListViewModel

@{
    ViewData["Title"] = "Games";
}
<div class="row m-1 p-1">
    <div class="col-2 mt-1">
        @foreach (var category in Model.Categories)
        {
            <a class="btn btn-block btn-secondary"
               asp-action="Index"
               asp-controller="Game"
               asp-route-category="@category.Name">
                @category.Name
            </a>
        }
    </div>

    <div class="col-10">
        @if (Model.Games.Items.Any())
        {
            @* game list *@
            @foreach (var item in Model.Games.Items)
            {
                <div class="card m-1 p-1">
                    <div class="p-1">
                        <h4>
                            @item.Name
                            <span class="badge badge-pill badge-primary" style="float: right">
                                <small>$@Math.Round(item.Price, 2)</small>
                            </span>
                        </h4>
                    </div>
                    <form id="@item.Id" asp-action="AddToCart"
                          asp-controller="Cart">
                        <input type="hidden" name="gameId" asp-for="@item.Id" />
                        <input type="hidden" name="returnUrl"
                               value="@(ViewContext.HttpContext.Request.GetEncodedPathAndQuery())" />
                        <span class="card-text p-1">
                            @foreach (var category in item.Categories)
                            {
                                <span class="badge badge-dark">@category.Name</span>
                            }
                            <br />
                            <span class="ml-1">@item.Description</span>

                            <button type="submit"
                                    class="btn btn-success btn-sm " style="float: right">
                                Add To Cart
                            </button>
                        </span>
                    </form>
                </div>
            }

            @if (Model.Games.HasPreviousPage || Model.Games.HasNextPage)
            {
                <div class="m-1 mt-3">
                    <nav>
                        <ul class="pagination">
                            <li class="page-item @(Model.Games.HasPreviousPage ? string.Empty : " disabled")">
                                <a class="page-link"
                                   asp-area="" asp-controller="Game"
                                   asp-action="Index" asp-route-p="@(Model.Games.PageNumber - 1)">Previous</a>
                            </li>
                            @for (var i = 1; i <= Model.Games.TotalPages; i++)
                            {
                                <li class="page-item @(Model.Games.PageNumber == i ? " active" : string.Empty)">
                                    <a class="page-link "
                                       asp-area="" asp-controller="Game"
                                       asp-action="Index" asp-route-p="@i">@i</a>
                                </li>
                            }
                            <li class="page-item @(Model.Games.HasNextPage ? string.Empty : " disabled")">
                                <a class="page-link"
                                   asp-area="" asp-controller="Game"
                                   asp-action="Index" asp-route-p="@(Model.Games.PageNumber + 1)">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>

            }
        }
        else
        {
            <div>
                <h1 class="display-4">No games available</h1>
            </div>
        }
    </div>
</div>