GameStore.WebUI/Areas/ViewComponents/CartSummaryViewComponent.cs
using GameStore.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Areas.ViewComponents
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System.Threading.Tasks;
using GameStore.Application.Queries.Category.GetAllCategories;
using GameStore.Application.Queries.Game.GetAllGames;
using GameStore.Application.ViewModels.Game;
using GameStore.Application.ViewModels.Pagination;
using Microsoft.AspNetCore.Mvc;

namespace GameStore.WebUI.Controllers
{
    public class GameController : BaseController
    {
        public async Task<ViewResult> Index(int? p, string category = null)
        {
            var games = await Mediator.Send(new GetAllGamesQuery
            {
                Pagination = new PageRequestViewModel(p ?? 1, 5),
                Category = category
            });
            var categories = await Mediator.Send(new GetAllCategoriesQuery());

            return View(new GamesListViewModel
            {
                Games = games,
                Categories = categories
            });
        }
    }
}

GameStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbar1" aria-controls="navbar1"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar1">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameStore</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home"
                           asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Game"
                           asp-route-category="@null" asp-action="Index">Games</a>
                    </li>
                </ul>
                <div>
                    @await Component.InvokeAsync("CartSummary")
                </div>
            </div>
        </nav>
    </header>

    <div class="pb-1">
        <partial name="_CookieConsentPartial" />
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="height: 4rem;">
        <div class="container">
            &copy; 2019 - GameStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/fontawesome.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>